server:
  port: 8001
  servlet:
    contextPath: /api/

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        readCapacity: 5
        writeCapacity: 5

product-scraper:
  aws:
    region: eu-west-1