server:
  port: 8001

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        readCapacity: 5
        writeCapacity: 5
  cache:
    type: redis

diet-advisor:
  aws:
    region: eu-west-1
  kafka:
    client:
      id: diet-advisor-product-scraper
    consumer:
      group-id: products-scrape-job-group
      auto-offset-reset: earliest
    topic:
      products-scrape-job: products-scrape-job-topic
  redis:
    cache:
      ttl-seconds: 604800
  selenium:
    strength-factory:
      email:
      password: