package pl.dietadvisor.productscraper.ProductScraper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.dietadvisor.productscraper.ProductScraper.enums.ProductScrapeJobState;
import pl.dietadvisor.productscraper.ProductScraper.util.converter.dynamodb.LocalDateTimeConverter;
import pl.dietadvisor.productscraper.ProductScraper.util.converter.dynamodb.ProductScrapeJobStateConverter;

import java.time.LocalDateTime;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "product-scrape-jobs")
public class ProductScrapeJob {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBTypeConverted(converter = ProductScrapeJobStateConverter.class)
    private ProductScrapeJobState state;
    private String errorMessage;
    private Integer scrapedProductsNumber;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt;
}
